### ISSUE TITLE
For ScrollViews, contentOffset should not be added to point, otherwise causing error.

### ISSUE THREAD

**Issue by rikumi** [CroPort/3DTouchManager#1]
in [CP3DTouchManager.m:119](https://github.com/CroPort/3DTouchManager/blob/master/3DTouchManager/CP3DTouchManager.m#L119)

When I leave out 'offset.x + ' and 'offset.y + ' here, the appearance in ScrollViews will be normal. Otherwise when you scroll down or left to create an offset, the function viewAtTouchPoint will return bad result.

**Comment by CroPort** [comment]
Thx, I found the bounds of scrollview embodied both the `contentOffset` and `adjustedContentInset` property(added in iOS11), so there is no need to make any calculation with UIScrollView,I've fixed it in the comming version.
